spring:
  datasource:
    url: jdbc:mysql://database-1.cf6wqwqimxyb.ap-northeast-2.rds.amazonaws.com:3306/food_db
    username: admin
    password: 21052105hello#
  jpa:
    show-sql: true


server:
  port: 80