spring:
  profiles:
    active: dev

jwt:
  secret: dkdowkdksjekwodkskdowkdfjwkdksoedkdsokdkdkdoskdksodkdkdok

cloud:
  aws:
    credentials: ### aws키로 채울것
      access-key: 
      secret-key: 
    s3:
      bucket: block-review-service
      region: ap-northeast-2